import { Be_Vietnam_Pro } from 'next/font/google';
import type { Metadata } from "next";
import "./globals.css";
import 'animate.css';

// Load the "Be Vietnam Pro" font
const beVietnamPro = Be_Vietnam_Pro({
  subsets: ['latin'],
  weight: ['400', '500', '700'], // Define the font weights you want to use
  variable: '--font-vietnam-pro', // Define a CSS variable for easy use
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={beVietnamPro.variable}>
      <body className="antialiased font-sans">
        {children}
      </body>
    </html>
  );
}
